// Generated by CoffeeScript 1.9.0
var a, correct, i, j, k, num, q, q_num, q_num_max, quiz_fn, quiz_fn_after, r, s, startQuiz, vans, _i, _j, _k;

vans = ['とり', 'りんご', 'DOG', 'LIFE', 'しょかく', 'くま', 'なし', 'CAT', 'EGG', 'ゆめ', 'さかな', 'いちご', 'RED', 'くるま', 'はな', 'MILK', 'ずぼん', 'やま', 'かわ', 'とまと', 'PEN', 'ゆき', 'いぬ', 'せみ'];

a = [];

q = [];

num = 0;

q_num = 0;

q_num_max = 4;

correct = 0;

for (i = _i = 0; 0 <= q_num_max ? _i <= q_num_max : _i >= q_num_max; i = 0 <= q_num_max ? ++_i : --_i) {
  q[i] = [];
  for (j = _j = 0; 0 <= q_num_max ? _j <= q_num_max : _j >= q_num_max; j = 0 <= q_num_max ? ++_j : --_j) {
    r = Math.floor(Math.random() * vans.length);
    q[i][j] = vans[r];
    vans.splice(r, 1);
  }
  q[i];
}

for (k = _k = 0; 0 <= q_num_max ? _k <= q_num_max : _k >= q_num_max; k = 0 <= q_num_max ? ++_k : --_k) {
  s = Math.floor(Math.random() * q_num_max);
  a[k] = q[k][r];
}

console.log(a);

console.log(q);

quiz_fn_after = function() {
  return $("#return").show();
};

quiz_fn = function(a) {
  var timer;
  console.log(a);
  startQuiz(a);
  return timer = setTimeout(quiz_fn_after, 5000);
};

$('#to_ans').click(function() {
  var _l, _ref;
  $("#return").hide();
  for (i = _l = 0, _ref = q_num_max - 1; 0 <= _ref ? _l <= _ref : _l >= _ref; i = 0 <= _ref ? ++_l : --_l) {
    $("#ans #btn" + i).val(q[q_num][i]);
  }
  return $("#ans").show();
});

$("#repeat").click(function() {
  $("#return").hide();
  return quiz_fn(a[q_num]);
});

$("#ans input").click(function() {
  if ($(this).val() === a[q_num]) {
    ++correct;
    $("#ans_crct").html("正解");
  } else {
    $("#ans_crct").html("残念、正解は " + a[q_num]);
  }
  $("#ans").hide();
  $("#ans_aft").show();
  return ++q_num;
});

$('#reload').click(function() {
  return location.reload();
});

$('#start,#start_next').click(function() {
  if (q_num > q_num_max) {
    $('#quizNum').hide();
    $("#ans_aft").hide();
    $("#last").show();
    $('#last_msg').html(q_num_max + 1 + "問中" + correct + "正解");
    return;
  }
  $("#first").hide();
  $("#ans_aft").hide();
  $("#quizNum").show();
  num = 0;
  $("#start").hide();
  $('#quizNum').html("第" + (q_num + 1) + "問");
  quiz_fn(a[q_num]);
});

startQuiz = function(q) {
  console.log(q);
  $.ajax({
    type: 'POST',
    url: '/text',
    data: {text:q}
  }).done(function(data) {}).fail(function(data) {}).always(function(data) {});
};
